#!/usr/bin/env python3
"""
OpenDoge 电机标定工具 — 计算 JointCalibration.offset 补偿值。

补偿电机编码器零点与 URDF 参考角度之间的偏差。此工具**绝不发送 COMM_SET_ZERO**,
只读取 mechPos (0x7019) 计算软件偏移量, 写入 deploy 配置文件。

参考角度 (来自 C++ defaultJointPosition / UniLab scene_flat.xml):
  hip        0.0 rad  (全部四条腿)
  thigh      0.5 rad  (前腿),  0.7 rad  (后腿)
  calf      -1.3 rad  (全部四条腿)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
快速使用
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  交互式 (逐关节标定, 推荐首次使用):
    python3 hardware/motor/el05_calibrate.py --channel can0

  批量模式 (机器人已处于站立姿态):
    python3 hardware/motor/el05_calibrate.py --channel can0 --batch

  注意: 此工具只读位置不控制电机, 需人工将关节摆到参考角度后按 Enter 读数。
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

  # Verify existing calibration
  python3 hardware/motor/el05_calibrate.py --channel can0 --verify

  # Dry-run (no CAN — validates logic)
  python3 hardware/motor/el05_calibrate.py --dry-run

Output is printed to stdout in key=value format ready to append to
opendoge_deploy.conf.
"""

from __future__ import annotations

import argparse
import sys

# Reuse CAN primitives from the motor menu tool.
from el05_motor_menu import (
    DEFAULT_MOTORS,
    IDX_MECH_POS,
    El05Bus,
    clamp,
    motor_label,
)

# ── reference angles per joint ──────────────────────────────────────
# These MUST match defaultJointPosition() in types.hpp.
# Order: FL_hip, FL_thigh, FL_calf, FR_hip, FR_thigh, FR_calf,
#         RL_hip, RL_thigh, RL_calf, RR_hip, RR_thigh, RR_calf
REFERENCE_ANGLES = [
    0.0, 0.5, -1.3,   # FL
    0.0, 0.5, -1.3,   # FR
    0.0, 0.7, -1.3,   # RL
    0.0, 0.7, -1.3,   # RR
]

DEFAULT_DIRECTION = 1.0  # default JointCalibration.direction
CAN_TIMEOUT = 1.0        # seconds to wait for param read


def compute_offset(
    mech_pos: float, ref_angle: float, direction: float
) -> float:
    """Compute the JointCalibration.offset for one motor.

    logicalPos = direction * (motor_pos - offset)
    => offset = motor_pos - direction * ref_angle

    When direction == 1.0:  offset = mech_pos - ref_angle
    When direction == -1.0: offset = mech_pos + ref_angle
    """
    return mech_pos - direction * ref_angle


def compute_logical(
    mech_pos: float, offset: float, direction: float
) -> float:
    """Apply calibration to get logical (URDF) position."""
    return direction * (mech_pos - offset)


def print_header() -> None:
    print("# OpenDoge motor calibration offsets")
    print("# Generated by el05_calibrate.py")
    print("# Append these lines to your opendoge_deploy.conf\n")


def interactive_calibrate(
    bus: El05Bus, motors: list[tuple[str, int]], dry_run: bool = False
) -> dict[str, float]:
    """Guide operator through each joint one at a time."""
    offsets: dict[str, float] = {}

    for idx, (name, motor_id) in enumerate(motors):
        ref = REFERENCE_ANGLES[idx]
        direction = DEFAULT_DIRECTION

        print(f"\n{'='*60}")
        print(f"Joint {idx+1}/12: {name} (motor_id={motor_id})")
        print(f"  Reference angle: {ref:+.3f} rad")
        print(f"  Direction: {direction:+.0f}")
        print()
        print(f"  ACTION: Manually position {name} to its URDF reference")
        print(f"         angle ({ref:+.3f} rad), then press Enter.")

        if dry_run:
            input("  [dry-run] Press Enter to simulate...")
            print(f"  [dry-run] Simulated mechPos = ref = {ref:+.3f} rad")
            offsets[name] = 0.0
            continue

        input("  Press Enter when ready...")

        # Read current mechanical position
        mech_pos = bus.read_param_float(motor_id, IDX_MECH_POS, timeout=CAN_TIMEOUT)
        if mech_pos is None:
            print(f"  ERROR: no response from {name} (id={motor_id})")
            print(f"  Skipping. Check CAN connection and retry.")
            continue

        offset = compute_offset(mech_pos, ref, direction)
        logical = compute_logical(mech_pos, offset, direction)
        error = logical - ref

        print(f"  mechPos = {mech_pos:+.4f} rad")
        print(f"  computed offset = {offset:+.4f} rad")
        print(f"  logical position after offset = {logical:+.4f} rad")
        print(f"  error vs reference = {error:+.4f} rad ({abs(error)*180/3.14159:.1f}°)")

        if abs(error) > 0.01:
            print(f"  WARNING: error > 0.01 rad — verify joint is at reference angle")
            if input("  Accept this offset anyway? [y/N]: ").strip().lower() != "y":
                print("  Skipped.")
                continue

        offsets[name] = offset
        print(f"  ✓ {name} offset = {offset:+.4f}")

    return offsets


def batch_calibrate(
    bus: El05Bus, motors: list[tuple[str, int]], dry_run: bool = False
) -> dict[str, float]:
    """Read all 12 motors at once (robot in standing pose)."""
    offsets: dict[str, float] = {}

    if dry_run:
        print("[dry-run] Simulating batch calibration...")
        for idx, (name, motor_id) in enumerate(motors):
            ref = REFERENCE_ANGLES[idx]
            offsets[name] = 0.0
            print(f"  {name}: ref={ref:+.3f} → offset=0.0000")
        return offsets

    print("\nPlace the robot in its default standing pose,")
    print("then press Enter to capture all 12 motor positions.")
    input("Press Enter when ready...")

    print("\nReading positions...")
    for idx, (name, motor_id) in enumerate(motors):
        ref = REFERENCE_ANGLES[idx]
        direction = DEFAULT_DIRECTION

        mech_pos = bus.read_param_float(motor_id, IDX_MECH_POS, timeout=CAN_TIMEOUT)
        if mech_pos is None:
            print(f"  {name} (id={motor_id}): NO RESPONSE — skipped")
            continue

        offset = compute_offset(mech_pos, ref, direction)
        logical = compute_logical(mech_pos, offset, direction)
        error = logical - ref
        offsets[name] = offset

        flag = " ✓" if abs(error) < 0.05 else " ?"
        print(
            f"  {name:20s}  mechPos={mech_pos:+8.4f}  "
            f"offset={offset:+8.4f}  logical={logical:+8.4f}  "
            f"err={error:+.4f}{flag}"
        )

    return offsets


def verify_calibration(
    bus: El05Bus,
    motors: list[tuple[str, int]],
    offsets_map: dict[str, float],
    dry_run: bool = False,
) -> None:
    """Re-read positions and check logical vs reference."""
    print("\nVerification — comparing logical positions against reference angles:\n")
    print(f"  {'Joint':20s} {'mechPos':>9s} {'offset':>9s} {'logical':>9s} {'ref':>9s} {'error':>9s}")
    print(f"  {'-'*20} {'-'*9} {'-'*9} {'-'*9} {'-'*9} {'-'*9}")

    max_error = 0.0
    for idx, (name, motor_id) in enumerate(motors):
        ref = REFERENCE_ANGLES[idx]
        offset = offsets_map.get(name, 0.0)
        direction = DEFAULT_DIRECTION

        if dry_run:
            mech_pos = ref + offset  # simulate perfect alignment
        else:
            mech_pos = bus.read_param_float(motor_id, IDX_MECH_POS, timeout=CAN_TIMEOUT)
            if mech_pos is None:
                print(f"  {name:20s}  NO RESPONSE")
                continue

        logical = compute_logical(mech_pos, offset, direction)
        error = logical - ref
        max_error = max(max_error, abs(error))

        flag = ""
        if abs(error) > 0.10:
            flag = " ← CHECK"
        elif abs(error) > 0.05:
            flag = " ← re-check?"

        print(
            f"  {name:20s} {mech_pos:+9.4f} {offset:+9.4f} "
            f"{logical:+9.4f} {ref:+9.4f} {error:+9.4f}{flag}"
        )

    print(f"\n  Max absolute error: {max_error:.4f} rad ({max_error*180/3.14159:.1f}°)")
    if max_error > 0.10:
        print("  WARNING: Large errors detected. Recalibrate affected joints.")
    elif max_error > 0.05:
        print("  Acceptable for initial testing. Fine-tune if needed.")
    else:
        print("  All joints within 0.05 rad — calibration looks good.")


def load_existing_offsets(config_path: str) -> dict[str, float]:
    """Parse existing joint.*.offset values from a deploy config file."""
    offsets: dict[str, float] = {}
    try:
        with open(config_path) as f:
            for line in f:
                line = line.split("#")[0].strip()
                if not line or "=" not in line:
                    continue
                key, value = line.split("=", 1)
                key = key.strip()
                value = value.strip()
                if key.startswith("joint.") and key.endswith(".offset"):
                    # joint.FL_hip_joint.offset → FL_hip_joint
                    name = key[len("joint."):-len(".offset")]
                    offsets[name] = float(value)
    except FileNotFoundError:
        pass
    return offsets


def print_offsets_config(offsets: dict[str, float]) -> None:
    """Print offsets in key=value format for the deploy config."""
    print_header()
    for name in sorted(offsets.keys()):
        print(f"joint.{name}.offset={offsets[name]:+.6f}")


def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="OpenDoge motor calibration — compute JointCalibration offsets",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --channel can0                    # interactive calibration
  %(prog)s --channel can0 --batch            # batch (robot in standing pose)
  %(prog)s --channel can0 --config deploy.conf --verify  # verify existing
  %(prog)s --dry-run                          # validate logic, no CAN
        """,
    )
    p.add_argument("--channel", default="can0", help="SocketCAN interface (default: can0)")
    p.add_argument("--master-id", default="0xfd", help="Host CAN ID (default: 0xfd)")
    p.add_argument("--config", help="Path to opendoge_deploy.conf for --verify")
    p.add_argument("--batch", action="store_true", help="Batch mode: read all 12 at once")
    p.add_argument("--verify", action="store_true", help="Verify existing offsets from --config")
    p.add_argument("--dry-run", action="store_true", help="Simulate without CAN hardware")
    return p


def main() -> int:
    args = build_arg_parser().parse_args()

    motors = list(DEFAULT_MOTORS)
    if len(motors) != 12:
        print("ERROR: DEFAULT_MOTORS list must have exactly 12 entries")
        return 1
    if len(REFERENCE_ANGLES) != 12:
        print("ERROR: REFERENCE_ANGLES list must have exactly 12 entries")
        return 1

    dry_run = args.dry_run

    if dry_run:
        print("=== DRY-RUN MODE (no CAN traffic) ===\n")

    # ── verify mode: check existing offsets ──
    if args.verify:
        if not args.config:
            print("ERROR: --verify requires --config <path>")
            return 1
        offsets = load_existing_offsets(args.config)
        if not offsets:
            print(f"No joint.*.offset keys found in {args.config}")
            return 1
        print(f"Loaded {len(offsets)} offsets from {args.config}")

        bus = None if dry_run else El05Bus(args.channel, int(str(args.master_id), 0))
        if bus is not None:
            try:
                bus.open()
            except OSError as exc:
                print(f"Failed to open {args.channel}: {exc}")
                return 1
        try:
            verify_calibration(bus, motors, offsets, dry_run)
        finally:
            if bus is not None:
                bus.close()
        return 0

    # ── calibration mode ──
    bus = None if dry_run else El05Bus(args.channel, int(str(args.master_id), 0))
    if bus is not None:
        try:
            bus.open()
        except OSError as exc:
            print(f"Failed to open {args.channel}: {exc}")
            print("Check: sudo ip link set can0 type can bitrate 1000000 && sudo ip link set up can0")
            return 1

    try:
        if args.batch:
            offsets = batch_calibrate(bus, motors, dry_run)
        else:
            offsets = interactive_calibrate(bus, motors, dry_run)

        if not offsets:
            print("\nNo offsets computed.")
            return 1

        print(f"\n{'='*60}")
        print(f"Calibration complete — {len(offsets)}/12 joints calibrated.")
        print()
        print_offsets_config(offsets)
        print(f"\n# Append the lines above to your opendoge_deploy.conf")

    finally:
        if bus is not None:
            bus.close()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
